### PR TITLE
jubilatious1

### PR DESCRIPTION
**Pull request by jubilatious1**

### CODE REVIEW

**Comment by vrurg** [comment]
Could you, please, also update the voting form at `nominations/2020/voting-form.md`?

**Comment by jubilatious1** [comment]
Thanks, Vadim! On its way.

**Comment by JJ** [comment]
Sorry, I missed it. Thanks @tbrowder

**Comment by jubilatious1** [comment]
Thank you, @tbrowder and @JJ !

**Comment by tbrowder** [comment]
On Sat, Sep 5, 2020 at 07:15 Juan Julián Merelo Guervós <
notifications@github.com> wrote:

>
> Sorry, I missed it. Thanks @tbrowder <https://github.com/tbrowder>
>
My pleasure. Could you ask nominees to please either manually edit files to
less than 80-character lines or rename docs to X.md so lines are visible
without horizontal scrolling?

Thanks.

**Comment by jubilatious1** [comment]
@tbrowder, apologies on the formatting. 

Could I ask you to rename the nomination file to add a *.md extension? I checked the box "Allow edits from maintainers" specifically to allow formatting changes. So I've given permission here, and also when I first submitted the PR. 

Otherwise, I'll have to redo the PR and get someone to commit. Thx.

**Comment by tbrowder** [comment]
On Sat, Sep 5, 2020 at 08:10 jubilatious1 <notifications@github.com> wrote

>
> Could I ask you to rename the nomination file to add a *.md extension? I
> checked the box "Allow edits from maintainers" specifically to allow
> formatting changes. So I've given permission here, and also when I first
> submitted the PR.
>
You bet.

-Tom

**Pull request merged**
